(define (problem lunar-mission3-test)
  (:domain lunar-extended-fixed)
  (:objects rover1 rover2 lander1 lander2 alice bob way1 way2 way3 way4 way5 way6)
  (:init
    (lander-at lander1 way2)
    (lander-at lander2 way6)
    (assigned rover1 lander1)
    (assigned rover2 lander2)
    (deployed rover1)
    (rover-at rover1 way2)
    (memory-free rover1)
    (memory-free rover2)
    (sample-at way1)
    (sample-at way5)
    (path way1 way2) (path way2 way1)
    (path way2 way3) (path way3 way2)
    (path way3 way4) (path way4 way3)
    (path way4 way5) (path way5 way4)
    (path way5 way6) (path way6 way5)
    (path way2 way5) (path way5 way2)
    (path way3 way6) (path way6 way3)
    (astronaut-in-dock alice lander1)
    (astronaut-in-control bob lander2)
  )
  (:goal (and (image-saved rover1 way3) (scan-saved rover1 way4) (image-saved rover2 way2) (scan-saved rover2 way6) (sample-stored lander1) (sample-stored lander2)))
)
